
namespace: nimbus

frontend:
  name: nimbus-frontend
  image: nimbus-frontend
  tag: phase4
  replicas: 1
  containerPort: 3000
  servicePort: 3000

backend:
  name: nimbus-backend
  image: nimbus-backend
  tag: phase4
  replicas: 1
  containerPort: 8000
  servicePort: 8000

  # IMPORTANT: do not commit real secrets here.
  # In Minikube we will inject these safely (later) without leaking values.
  env:
    JWT_ALGORITHM: "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
    AUTH_SERVER_URL: "http://localhost:3000"
